create or replace table bids_request
engine MergeTree
primary key (dateTime, site_id, device_os)
as
with 	arrayJoin(JSONExtractArrayRaw(request, 'imp')) as imp_json,
			if(JSONHas(request, 'site'), 'site', 'app') as site_or_app
select 	dateTime,
				auctionId,
				JSONExtractString(request, 'id') as id,
				JSONExtractUInt(request, 'at') as at,
				JSONExtractUInt(request, 'test') as test,
				JSONExtractUInt(request, 'tmax') as tmax,
				replaceAll(arrayStringConcat(JSONExtractArrayRaw(request, 'wseat'), ','), '"', '') as wseat,
				replaceAll(arrayStringConcat(JSONExtractArrayRaw(request, 'bseat'), ','), '"', '') as bseat,
				replaceAll(arrayStringConcat(JSONExtractArrayRaw(request, 'allimps'), ','), '"', '') as allimps,
				replaceAll(arrayStringConcat(JSONExtractArrayRaw(request, 'cur'), ','), '"', '') as cur,
				replaceAll(arrayStringConcat(JSONExtractArrayRaw(request, 'wlang'), ','), '"', '') as wlang,
				replaceAll(arrayStringConcat(JSONExtractArrayRaw(request, 'bcat'), ','), '"', '') as bcat,
				replaceAll(arrayStringConcat(JSONExtractArrayRaw(request, 'badv'), ','), '"', '') as badv,
				replaceAll(arrayStringConcat(JSONExtractArrayRaw(request, 'bapp'), ','), '"', '') as bapp,
				JSONExtractRaw(request, 'ext') as ext,
				JSONExtractUInt(request, 'source', 'fd') as source_fd,
				JSONExtractString(request, 'source', 'tid') as source_tid,
				JSONExtractString(request, 'source', 'pchain') as source_pchain,
				JSONExtractRaw(request, 'source', 'ext') as source_ext,
				JSONExtractUInt(request, 'regs', 'coppa') as regs_coppa,
				JSONExtractRaw(request, 'regs', 'ext') as regs_ext,
				JSONExtractString(imp_json, 'id') as imp_id,
				JSONExtractString(imp_json, 'displaymanager') as imp_displaymanager,
				JSONExtractString(imp_json, 'displaymanagerver') as imp_displaymanagerver,
				JSONExtractUInt(imp_json, 'instl') as imp_instl,
				JSONExtractString(imp_json, 'tagid') as imp_tagid,
				JSONExtractFloat(imp_json, 'bidfloor') as imp_bodfloor,
				JSONExtractString(imp_json, 'bidfloorcur') as imp_bidfloorcur,
				JSONExtractUInt(imp_json, 'clickbrowser') as imp_clickbrowser,
				JSONExtractUInt(imp_json, 'secure') as imp_secure,
				replaceAll(arrayStringConcat(JSONExtractArrayRaw(imp_json, 'iframebuster'), ','), '"', '') as imp_iframebuster,
				JSONExtractUInt(imp_json, 'exp') as imp_exp,
				JSONHas(imp_json, 'pmp') as is_imp_pmp,
				JSONExtractUInt(imp_json, 'pmp', 'private_auction') as imp_pmp_private_auction,
				JSONExtractArrayRaw(imp_json, 'pmp', 'deals') as imp_pmp_deals,
				JSONExtractRaw(imp_json, 'pmp', 'ext') as imp_pmp_ext,
				JSONExtractRaw(imp_json, 'ext') as imp_ext,
				JSONExtractArrayRaw(imp_json, 'metric') as imp_metric,
				JSONHas(imp_json, 'banner') as imp_is_banner,
				JSONHas(imp_json, 'video') as imp_is_video,
				JSONHas(imp_json, 'native') as imp_is_native,
				JSONHas(imp_json, 'audio') as imp_is_audio,
				JSONExtractArrayRaw(imp_json, 'banner', 'format') as imp_b_format,
				JSONExtractUInt(imp_json, 'banner', 'w') as imp_b_w,
				JSONExtractUInt(imp_json, 'banner', 'h') as imp_b_h,
				arrayMap(x -> toUInt32(x), JSONExtractArrayRaw(imp_json, 'banner', 'btype')) as imp_b_btype,
				arrayMap(x -> toUInt32(x), JSONExtractArrayRaw(imp_json, 'banner', 'battr')) as imp_b_battr,
				JSONExtractUInt(imp_json, 'banner', 'pos') as imp_b_pos,
				replaceAll(arrayStringConcat(JSONExtractArrayRaw(imp_json, 'banner', 'mimes'), ','), '"', '') as imp_b_mimes,
				JSONExtractUInt(imp_json, 'banner', 'topframe') as imp_b_topframe,
				arrayMap(x -> toUInt32(x), JSONExtractArrayRaw(imp_json, 'banner', 'expdir')) as imp_b_expdir,
				arrayMap(x -> toUInt32(x), JSONExtractArrayRaw(imp_json, 'banner', 'api')) as imp_b_api,
				JSONExtractString(imp_json, 'banner', 'id') as imp_b_id,
				JSONExtractUInt(imp_json, 'banner', 'vcm') as imp_b_vcm,
				JSONExtractRaw(imp_json, 'banner', 'ext') as imp_b_ext,
				replaceAll(arrayStringConcat(JSONExtractArrayRaw(imp_json, 'video', 'mimes'), ','), '"', '') as imp_v_mimes,
				JSONExtractUInt(imp_json, 'video', 'minduration') as imp_v_minduration,
				JSONExtractUInt(imp_json, 'video', 'maxduration') as imp_v_maxduration,
				arrayMap(x -> toUInt32(x), JSONExtractArrayRaw(imp_json, 'video', 'protocols')) as imp_v_protocols,
				JSONExtractUInt(imp_json, 'video', 'w') as imp_v_w,
				JSONExtractUInt(imp_json, 'video', 'h') as imp_v_h,
				JSONExtractUInt(imp_json, 'video', 'startdelay') as imp_v_startdelay,
				JSONExtractUInt(imp_json, 'video', 'placement') as imp_v_placement,
				JSONExtractUInt(imp_json, 'video', 'linearity') as imp_v_linearity,
				JSONExtractUInt(imp_json, 'video', 'skip') as imp_v_skip,
				JSONExtractUInt(imp_json, 'video', 'skipmin') as imp_v_skipmin,
				JSONExtractUInt(imp_json, 'video', 'skipafter') as imp_v_skipafter,
				JSONExtractUInt(imp_json, 'video', 'sequence') as imp_v_sequence,
				arrayMap(x -> toUInt32(x), JSONExtractArrayRaw(imp_json, 'video', 'battr')) as imp_v_battr,
				JSONExtractUInt(imp_json, 'video', 'maxextended') as imp_v_maxextended,
				JSONExtractUInt(imp_json, 'video', 'minbitrate') as imp_v_minbitrate,
				JSONExtractUInt(imp_json, 'video', 'maxbitrate') as imp_v_maxbitrate,
				JSONExtractUInt(imp_json, 'video', 'boxingallowed') as imp_v_boxingallowed,
				arrayMap(x -> toUInt32(x), JSONExtractArrayRaw(imp_json, 'video', 'playbackmethod')) as imp_v_playbackmethod,
				JSONExtractUInt(imp_json, 'video', 'playbackend') as imp_v_playbackend,
				arrayMap(x -> toUInt32(x), JSONExtractArrayRaw(imp_json, 'video', 'delivery')) as imp_v_delivery,
				JSONExtractUInt(imp_json, 'video', 'pos') as imp_v_pos,
				JSONExtractArrayRaw(imp_json, 'video', 'companionad') as imp_v_companioned,
				arrayMap(x -> toUInt32(x), JSONExtractArrayRaw(imp_json, 'video', 'api')) as imp_v_api,
				arrayMap(x -> toUInt32(x), JSONExtractArrayRaw(imp_json, 'video', 'companiontype')) as imp_v_companiontype,
				JSONExtractRaw(imp_json, 'video', 'ext') as imp_v_ext,
				JSONExtractString(imp_json, 'native', 'request') as imp_n_request,
				JSONExtractString(imp_json, 'native', 'ver') as imp_n_ver,
				arrayMap(x -> toUInt32(x), JSONExtractArrayRaw(imp_json, 'native', 'api')) as imp_n_api,
				arrayMap(x -> toUInt32(x), JSONExtractArrayRaw(imp_json, 'native', 'battr')) as imp_n_battr,
				JSONExtractRaw(imp_json, 'native', 'ext') as imp_n_ext,
				replaceAll(arrayStringConcat(JSONExtractArrayRaw(imp_json, 'audio', 'mimes'), ','), '"', '') as imp_a_mimes,
				JSONExtractUInt(imp_json, 'audio', 'minduration') as imp_a_minduration,
				JSONExtractUInt(imp_json, 'audio', 'maxduration') as imp_a_maxduration,
				arrayMap(x -> toUInt32(x), JSONExtractArrayRaw(imp_json, 'audio', 'protocols')) as imp_a_protocols,
				JSONExtractUInt(imp_json, 'audio', 'startdelay') as imp_a_startdelay,
				JSONExtractUInt(imp_json, 'audio', 'sequence') as imp_a_sequence,
				arrayMap(x -> toUInt32(x), JSONExtractArrayRaw(imp_json, 'audio', 'battr')) as imp_a_battr,
				JSONExtractUInt(imp_json, 'audio', 'maxextended') as imp_a_maxextended,
				JSONExtractUInt(imp_json, 'audio', 'minbitrate') as imp_a_minbitrate,
				JSONExtractUInt(imp_json, 'audio', 'maxbitrate') as imp_a_maxbitrate,
				arrayMap(x -> toUInt32(x), JSONExtractArrayRaw(imp_json, 'audio', 'delivery')) as imp_a_delivery,
				JSONExtractArrayRaw(imp_json, 'audio', 'companionad') as imp_a_companionad,
				arrayMap(x -> toUInt32(x), JSONExtractArrayRaw(imp_json, 'audio', 'api')) as imp_a_api,
				arrayMap(x -> toUInt32(x), JSONExtractArrayRaw(imp_json, 'audio', 'companiontype')) as imp_a_companiontype,
				JSONExtractUInt(imp_json, 'audio', 'maxseq') as imp_a_maxseq,
				JSONExtractUInt(imp_json, 'audio', 'feed') as imp_a_feed,
				JSONExtractUInt(imp_json, 'audio', 'stitched') as imp_a_stitched,
				JSONExtractUInt(imp_json, 'audio', 'nvol') as imp_a_nvol,
				JSONExtractRaw(imp_json, 'audio', 'ext') as imp_a_ext,
				JSONExtractString(request, 'user', 'id') as user_id,
				JSONExtractString(request, 'user', 'buyeruid') as user_buyeruid,
				JSONExtractUInt(request, 'user', 'yob') as user_yob,
				JSONExtractString(request, 'user', 'gender') as user_gender,
				JSONExtractString(request, 'user', 'keywords') as user_keywords,
				JSONExtractString(request, 'user', 'customedata') as user_customedata,
				JSONExtractString(request, 'user', 'geo') as user_geo,
				JSONExtractArrayRaw(request, 'user', 'data') as user_data,
				JSONExtractRaw(request, 'user', 'ext') as user_ext,
				JSONHas(request, 'site') as is_site,
				JSONHas(request, 'app') as is_app,
				JSONExtractString(request, 'site', 'id') as site_id,
				JSONExtractString(request, 'site', 'name') as site_name,
				JSONExtractString(request, 'site', 'domain') as site_domain,
				replaceAll(arrayStringConcat(JSONExtractArrayRaw(request, 'site', 'cat'), ','), '"', '') as site_cat,
				replaceAll(arrayStringConcat(JSONExtractArrayRaw(request, 'site', 'sectioncat'), ','), '"', '') as site_sectioncat,
				replaceAll(arrayStringConcat(JSONExtractArrayRaw(request, 'site', 'pagecat'), ','), '"', '') as site_pagecat,
				JSONExtractString(request, 'site', 'page') as site_page,
				JSONExtractString(request, 'site', 'ref') as site_ref,
				JSONExtractString(request, 'site', 'search') as site_search,
				JSONExtractUInt(request, 'site', 'mobile') as site_mobile,
				JSONExtractUInt(request, 'site', 'privacypolicy') as site_privacypolicy,
				JSONExtractString(request, 'site', 'keywords') as site_keywords,
				JSONExtractRaw(request, 'site', 'ext') as site_ext,
				JSONExtractString(request, 'app', 'id') as app_id,
				JSONExtractString(request, 'app', 'name') as app_name,
				JSONExtractString(request, 'app', 'boundle') as app_boundle,
				JSONExtractString(request, 'app', 'domain') as app_domain,
				JSONExtractString(request, 'app', 'storeurl') as app_storeurl,
				replaceAll(arrayStringConcat(JSONExtractArrayRaw(request, 'app', 'cat'), ','), '"', '') as app_cat,
				replaceAll(arrayStringConcat(JSONExtractArrayRaw(request, 'app', 'sectioncat'), ','), '"', '') as app_sectioncat,
				replaceAll(arrayStringConcat(JSONExtractArrayRaw(request, 'app', 'pagecat'), ','), '"', '') as app_pagecat,
				JSONExtractString(request, 'app', 'ver') as app_ver,
				JSONExtractUInt(request, 'app', 'privacypolicy') as app_privacypolicy,
				JSONExtractUInt(request, 'app', 'paid') as app_paid,
				JSONExtractString(request, 'app', 'keywords') as app_keywords,
				JSONExtractRaw(request, 'app', 'ext') as app_ext,
				JSONExtractString(request, site_or_app, 'publisher', 'id') as publisher_id,
				JSONExtractString(request, site_or_app, 'publisher', 'name') as publisher_name,
				replaceAll(arrayStringConcat(JSONExtractArrayRaw(request, site_or_app, 'publisher', 'cat'), ','), '"', '') as publisher_cat,
				JSONExtractString(request, site_or_app, 'publisher', 'domain') as publisher_domain,
				JSONExtractRaw(request, site_or_app, 'publisher', 'ext') as publisher_ext,
				JSONExtractString(request, site_or_app, 'content', 'id') as content_id,
				JSONExtractUInt(request, site_or_app, 'content', 'episode') as content_episode,
				JSONExtractString(request, site_or_app, 'content', 'title') as content_title,
				JSONExtractString(request, site_or_app, 'content', 'series') as content_series,
				JSONExtractString(request, site_or_app, 'content', 'season') as content_season,
				JSONExtractString(request, site_or_app, 'content', 'artist') as content_artist,
				JSONExtractString(request, site_or_app, 'content', 'genre') as content_genre,
				JSONExtractString(request, site_or_app, 'content', 'album') as content_album,
				JSONExtractString(request, site_or_app, 'content', 'isrc') as content_isrc,
				JSONExtractString(request, site_or_app, 'content', 'url') as content_url,
				replaceAll(arrayStringConcat(JSONExtractArrayRaw(request, site_or_app, 'content', 'cat'), ','), '"', '') as content_cat,
				JSONExtractUInt(request, site_or_app, 'content', 'probq') as content_probq,
				JSONExtractUInt(request, site_or_app, 'content', 'context') as content_context,
				JSONExtractString(request, site_or_app, 'content', 'contentrating') as content_contentrating,
				JSONExtractString(request, site_or_app, 'content', 'userrating') as content_userrating,
				JSONExtractUInt(request, site_or_app, 'content', 'qagmediarating') as content_qagmediarating,
				JSONExtractString(request, site_or_app, 'content', 'keywords') as content_keywords,
				JSONExtractUInt(request, site_or_app, 'content', 'livestream') as content_livestream,
				JSONExtractUInt(request, site_or_app, 'content', 'sourcerelationship') as content_sourcerelationship,
				JSONExtractUInt(request, site_or_app, 'content', 'len') as content_len,
				JSONExtractString(request, site_or_app, 'content', 'language') as content_language,
				JSONExtractUInt(request, site_or_app, 'content', 'embeddale') as content_embeddable,
				JSONExtractArrayRaw(request, site_or_app, 'content', 'data') as content_data,
				JSONExtractRaw(request, site_or_app, 'content', 'ext') as content_ext,
				JSONExtractString(request, site_or_app, 'content', 'producer', 'id') as conent_producer_id,
				JSONExtractString(request, site_or_app, 'content', 'producer', 'name') as content_producer_name,
				replaceAll(arrayStringConcat(JSONExtractArrayRaw(request, site_or_app, 'content', 'producer', 'cat'), ','), '"', '') as content_producer_id,
				JSONExtractString(request, site_or_app, 'content', 'producer', 'domain') as content_producer_domain,
				JSONExtractRaw(request, site_or_app, 'content', 'producer', 'ext') as content_producer_ext,
				JSONExtractString(request, 'device', 'ua') as device_ua,
				JSONExtractUInt(request, 'device', 'dnt') as device_dnt,
				JSONExtractUInt(request, 'device', 'imt') as device_imt,
				JSONExtractString(request, 'device', 'ip') as device_ip,
				JSONExtractString(request, 'device', 'ipv6') as device_ipv6,
				JSONExtractUInt(request, 'device', 'devicetype') as device_devicetype,
				JSONExtractString(request, 'device', 'make') as device_make,
				JSONExtractString(request, 'device', 'model') as device_model,
				JSONExtractString(request, 'device', 'os') as device_os,
				JSONExtractString(request, 'device', 'osv') as device_osv,
				JSONExtractString(request, 'device', 'hwv') as device_hwv,
				JSONExtractUInt(request, 'device', 'h') as device_h,
				JSONExtractUInt(request, 'device', 'w') as device_w,
				JSONExtractUInt(request, 'device', 'ppi') as device_ppi,
				JSONExtractFloat(request, 'device', 'pxratio') as device_pxratio,
				JSONExtractUInt(request, 'device', 'js') as device_js,
				JSONExtractUInt(request, 'device', 'geofetch') as device_geofetch,
				JSONExtractString(request, 'device', 'flashver') as device_flashver,
				JSONExtractString(request, 'device', 'language') as device_language,
				JSONExtractString(request, 'device', 'carrier') as device_carrier,
				JSONExtractString(request, 'device', 'mccmnc') as device_mccmnc,
				JSONExtractUInt(request, 'device', 'connectiontype') as device_connectiontype,
				JSONExtractString(request, 'device', 'ifg') as device_ifg,
				JSONExtractString(request, 'device', 'didsha1') as device_didsha1,
				JSONExtractString(request, 'device', 'didmd5') as device_didmd5,
				JSONExtractString(request, 'device', 'dpidsha1') as device_dpidsha1,
				JSONExtractString(request, 'device', 'dpidmd5') as device_dpidmd5,
				JSONExtractString(request, 'device', 'macsha1') as device_macsha1,
				JSONExtractString(request, 'device', 'macmd5') as device_macmd5,
				JSONExtractRaw(request, 'device', 'ext') as device_ext,
				JSONExtractFloat(request, 'device', 'geo', 'lat') as device_geo_lat,
				JSONExtractFloat(request, 'device', 'geo', 'lon') as device_geo_lon,
				JSONExtractInt(request, 'device', 'geo', 'type') as device_geo_type,
				JSONExtractInt(request, 'device', 'geo', 'accuracy') as device_geo_accuracy,
				JSONExtractInt(request, 'device', 'geo', 'lastfix') as device_geo_lastfix,
				JSONExtractInt(request, 'device', 'geo', 'ipservice') as device_geo_ipservice,
				JSONExtractString(request, 'device', 'geo', 'country') as device_geo_country,
				JSONExtractString(request, 'device', 'geo', 'region') as device_geo_region,
				JSONExtractString(request, 'device', 'geo', 'regionfips104') as device_geo_regionfips104,
				JSONExtractString(request, 'device', 'geo', 'metro') as device_geo_metro,
				JSONExtractString(request, 'device', 'geo', 'city') as device_geo_city,
				JSONExtractString(request, 'device', 'geo', 'zip') as device_geo_zip,
				JSONExtractUInt(request, 'device', 'geo', 'utcoffset') as device_geo_utcoffset,
				JSONExtractRaw(request, 'device', 'geo', 'ext') as device_geo_ext
	from bids_local;
